/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package proxy

import (
	"context"
	"fmt"
	"log"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	"github.com/detiber/k8s-jumperless/utils/internal/proxy"
	"github.com/detiber/k8s-jumperless/utils/internal/proxy/config"
)

const (
	cfgPrefix         = "proxy"
	cfgBaudRate       = "baud-rate"
	cfgBufferSize     = "buffer-size"
	cfgVirtualPort    = "virtual-port"
	cfgRealPort       = "real-port"
	cfgEmulatorConfig = "emulator-config"
)

func NewProxyCommand(v *viper.Viper, parentLogger *log.Logger) *cobra.Command {
	logger := log.New(parentLogger.Writer(), parentLogger.Prefix()+" [proxy]", parentLogger.Flags())
	cmd := &cobra.Command{
		Use:   "proxy",
		Short: "Jumperless proxy",
		Long:  `A proxy sends configured commands to a Jumperless device over a serial port`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			ctx := cmd.Context()
			return runProxy(ctx, v, logger)
		},
	}

	// Set default config
	defaultConfig := config.NewDefaultConfig()
	v.SetDefault(cfgPrefix, defaultConfig)

	// Command-line flags
	cmd.Flags().Int(cfgBufferSize, defaultConfig.BufferSize, "buffer size for reading from the real serial port")
	_ = v.BindPFlag(cfgPrefix+"."+cfgBufferSize, cmd.Flags().Lookup(cfgBufferSize))

	cmd.Flags().String(cfgVirtualPort, defaultConfig.VirtualPort,
		"symlink for virtual serial port(if not specified, it will use the autogenerated virtual port)")
	_ = v.BindPFlag(cfgPrefix+"."+cfgVirtualPort, cmd.Flags().Lookup(cfgVirtualPort))

	cmd.Flags().String(cfgRealPort, defaultConfig.RealPort,
		"real serial port to use (if not specified, will attempt to auto-detect)")
	_ = v.BindPFlag(cfgPrefix+"."+cfgRealPort, cmd.Flags().Lookup(cfgRealPort))

	cmd.Flags().Int(cfgBaudRate, defaultConfig.BaudRate, "baud rate for the real serial port")
	_ = v.BindPFlag(cfgPrefix+"."+cfgBaudRate, cmd.Flags().Lookup(cfgBaudRate))

	cmd.Flags().String(cfgEmulatorConfig, defaultConfig.EmulatorConfig,
		"emulator config file to use to start an emulator if real-port is not specified")
	_ = v.BindPFlag(cfgPrefix+"."+cfgEmulatorConfig, cmd.Flags().Lookup(cfgEmulatorConfig))

	return cmd
}

func runProxy(ctx context.Context, v *viper.Viper, logger *log.Logger) error {
	proxyConfig := new(config.ProxyConfig)

	if err := v.Unmarshal(proxyConfig); err != nil {
		return fmt.Errorf("failed to unmarshal current config: %w", err)
	}

	logger.Printf("Starting Jumperless proxy with config: %+v", proxyConfig)

	// Create proxy
	p, err := proxy.New(proxyConfig, logger)
	if err != nil {
		return fmt.Errorf("failed to create proxy: %w", err)
	}

	proxyCtx, cancel := context.WithCancel(ctx)

	// Start proxy
	if err := p.Start(proxyCtx); err != nil {
		cancel()
		return fmt.Errorf("failed to start proxy: %w", err)
	}

	logger.Printf("Proxy started. Virtual serial port: %s", p.GetVirtualPortName())
	logger.Printf("Press Ctrl+C to stop")

	<-ctx.Done()
	cancel()

	logger.Printf("Stopping proxy...")
	if err := p.Stop(); err != nil {
		logger.Printf("Error stopping proxy: %v", err)
	}

	logger.Printf("proxy stopped")
	return nil
}
