/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package proxy

import (
	"context"
	"fmt"
	"log"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"

	"github.com/detiber/k8s-jumperless/utils/internal/proxy"
	"github.com/detiber/k8s-jumperless/utils/internal/proxy/config"
)

func NewProxyCommand(v *viper.Viper, parentLogger *log.Logger) *cobra.Command {
	logger := log.New(parentLogger.Writer(), parentLogger.Prefix()+" [proxy]", parentLogger.Flags())

	cmd := &cobra.Command{
		Use:   "proxy",
		Short: "Jumperless proxy",
		Long:  `A proxy sends configured commands to a Jumperless device over a serial port`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			ctx := cmd.Context()
			return runProxy(ctx, v, logger)
		},
	}

	// Command-line flags
	cmd.Flags().Int(config.FlagBufferSize, config.DefaultBufferSize, "buffer size for reading from the real serial port")
	_ = v.BindPFlag(config.ViperBufferSize, cmd.Flags().Lookup(config.FlagBufferSize))

	cmd.Flags().String(config.FlagVirtualPort, "",
		"symlink for virtual serial port(if not specified, it will use the autogenerated virtual port)")
	_ = v.BindPFlag(config.ViperVirtualPort, cmd.Flags().Lookup(config.FlagVirtualPort))

	cmd.Flags().String(config.FlagRealPort, "",
		"real serial port to use (if not specified, will attempt to auto-detect)")
	_ = v.BindPFlag(config.ViperRealPort, cmd.Flags().Lookup(config.FlagRealPort))

	cmd.Flags().Int(config.FlagBaudRate, config.DefaultBaudRate, "baud rate for the real serial port")
	_ = v.BindPFlag(config.ViperBaudRate, cmd.Flags().Lookup(config.FlagBaudRate))

	return cmd
}

func runProxy(ctx context.Context, v *viper.Viper, logger *log.Logger) error {
	proxyConfig := config.NewFromViper(v)

	logger.Printf("Starting Jumperless proxy with config: %+v", proxyConfig)

	// Create proxy
	p, err := proxy.New(proxyConfig, logger)
	if err != nil {
		return fmt.Errorf("failed to create proxy: %w", err)
	}

	recording, err := p.Run(ctx)
	if err != nil {
		return fmt.Errorf("failed to run proxy: %w", err)
	}

	logger.Printf("Recorded %d request/response pairs", len(recording))

	logger.Printf("proxy stopped")
	return nil
}
