// Code generated by "stringer -type=DACChannel"; DO NOT EDIT.

package v5alpha1

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DAC0-0]
	_ = x[DAC1-1]
	_ = x[TOP_RAIL-2]
	_ = x[BOTTOM_RAIL-3]
}

const _DACChannel_name = "DAC0DAC1TOP_RAILBOTTOM_RAIL"

var _DACChannel_index = [...]uint8{0, 4, 8, 16, 27}

func (i DACChannel) String() string {
	if i < 0 || i >= DACChannel(len(_DACChannel_index)-1) {
		return "DACChannel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DACChannel_name[_DACChannel_index[i]:_DACChannel_index[i+1]]
}
