//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v5alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DAC) DeepCopyInto(out *DAC) {
	*out = *in
	if in.Save != nil {
		in, out := &in.Save, &out.Save
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DAC.
func (in *DAC) DeepCopy() *DAC {
	if in == nil {
		return nil
	}
	out := new(DAC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Jumperless) DeepCopyInto(out *Jumperless) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Jumperless.
func (in *Jumperless) DeepCopy() *Jumperless {
	if in == nil {
		return nil
	}
	out := new(Jumperless)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Jumperless) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JumperlessHost) DeepCopyInto(out *JumperlessHost) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
	if in.SSHKeyRef != nil {
		in, out := &in.SSHKeyRef, &out.SSHKeyRef
		*out = new(v1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JumperlessHost.
func (in *JumperlessHost) DeepCopy() *JumperlessHost {
	if in == nil {
		return nil
	}
	out := new(JumperlessHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JumperlessList) DeepCopyInto(out *JumperlessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Jumperless, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JumperlessList.
func (in *JumperlessList) DeepCopy() *JumperlessList {
	if in == nil {
		return nil
	}
	out := new(JumperlessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JumperlessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JumperlessSpec) DeepCopyInto(out *JumperlessSpec) {
	*out = *in
	in.Host.DeepCopyInto(&out.Host)
	if in.OLED != nil {
		in, out := &in.OLED, &out.OLED
		*out = new(OLEDDisplay)
		(*in).DeepCopyInto(*out)
	}
	if in.DACS != nil {
		in, out := &in.DACS, &out.DACS
		*out = make([]DAC, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JumperlessSpec.
func (in *JumperlessSpec) DeepCopy() *JumperlessSpec {
	if in == nil {
		return nil
	}
	out := new(JumperlessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JumperlessStatus) DeepCopyInto(out *JumperlessStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JumperlessStatus.
func (in *JumperlessStatus) DeepCopy() *JumperlessStatus {
	if in == nil {
		return nil
	}
	out := new(JumperlessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OLEDDisplay) DeepCopyInto(out *OLEDDisplay) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OLEDDisplay.
func (in *OLEDDisplay) DeepCopy() *OLEDDisplay {
	if in == nil {
		return nil
	}
	out := new(OLEDDisplay)
	in.DeepCopyInto(out)
	return out
}
