---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - jumperless.detiber.us
  resources:
  - jumperlesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jumperless.detiber.us
  resources:
  - jumperlesses/finalizers
  verbs:
  - update
- apiGroups:
  - jumperless.detiber.us
  resources:
  - jumperlesses/status
  verbs:
  - get
  - patch
  - update
