virtualPort:
    port: /tmp/jumperless-proxy
    baudRate: 115200
    bufferSize: 1024
realPort:
    port: /dev/ttyUSB0
    baudRate: 115200
    bufferSize: 1024
recording:
    enabled: true
    outputFile: jumperless-recording.yaml
    outputFormat: yaml
    includeTimestamps: true
    bufferSize: 0
