name: _lint

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      go-version-file:
        required: true
        type: string
      go-cache-dependency-path:
        required: true
        type: string
      module-working-directory:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.go-version-file }}
          cache-dependency-path: ${{ inputs.go-cache-dependency-path }}
          cache: true

      - name: Tidy
        working-directory: ${{ inputs.module-working-directory }}
        run: go mod tidy

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0
          working-directory: ${{ inputs.module-working-directory }}
