name: Lint Emulator

permissions:
  contents: read

on:
  push:
    paths:
      - 'utils/jumperless-emulator/**'
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    paths:
      - 'utils/jumperless-emulator/**'

jobs:
  lint-emulator:
    uses: ./.github/workflows/_lint.yml
    with:
      go-version-file: "utils/jumperless-emulator/go.mod"
      go-cache-dependency-path: "utils/jumperless-emulator/go.sum"
      module-working-directory: "utils/jumperless-emulator"
