name: Lint

permissions:
  contents: read

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  lint:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
