name: Lint Utils

permissions:
  contents: read

on:
  push:
    paths:
      - 'utils/**'
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    paths:
      - 'utils/**'

jobs:
  lint-utils:
    uses: ./.github/workflows/_lint.yml
    with:
      go-version-file: "utils/go.mod"
      go-cache-dependency-path: "utils/go.sum"
      module-working-directory: "utils"
