name: Lint Emulator Integration

permissions:
  contents: read

on:
  push:
    paths:
      - 'utils/test/**'
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    paths:
      - 'utils/test/**'

jobs:
  lint-emulator-integration:
    uses: ./.github/workflows/_lint.yml
    with:
      go-version-file: "utils/test/go.mod"
      go-cache-dependency-path: "utils/test/go.sum"
      lint-working-directory: "utils/test"
