name: Lint

permissions:
  contents: read

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - 'utils/**'
  pull_request:
    paths-ignore:
      - 'utils/**'
jobs:
  lint:
    uses: ./.github/workflows/_lint.yml
    with:
      go-version-file: "go.mod"
      go-cache-dependency-path: "go.sum"
      lint-working-directory: ""
