name: Tests

permissions:
  contents: read

on:
  push:
    paths-ignore:
      - 'utils/**'
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    paths-ignore:
      - 'utils/**'

jobs:
  test:
    uses: ./.github/workflows/_test.yml
    with:
      go-version-file: "go.mod"
      go-cache-dependency-path: "go.sum"
      module-working-directory: ""
      target-name: "test"
